version: '3.8'

services:
  auth-db:
    image: postgres:16
    container_name: auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    depends_on:
      - auth-db
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: dev
    build:
      context: ../auth-service
      dockerfile: Dockerfile

volumes:
  auth_pgdata:
